from .analyze import (
    assign_review_cohort,
    calculate_cr10,
    calculate_cr5,
    calculate_entry_score,
    calculate_new_shop_share,
    calculate_price_summary,
    calculate_rank_window_metrics,
    calculate_recent_listing_share,
    calculate_unique_shop_penetration,
    classify_verdict,
)
from .ai import AIProvider, AIResult, AISettings, NullAIProvider, build_ai_provider, load_ai_settings
from .config import load_query_config, load_threshold_config
from .models import (
    CanonicalListing,
    CanonicalShop,
    EntryScoreResult,
    FamilyMetrics,
    PriceSummary,
    QueryDefinition,
    QueryMetrics,
    RankWindowMetrics,
    RawObservation,
    ResearchRun,
    ResearchVerdict,
)
from .normalize import build_canonical_listings, build_canonical_shops, normalize_listing_id
from .pilot import classify_capability_status, parse_active_listing_page, parse_active_listing_record, select_representative_pilot_queries

__all__ = [
    "__version__",
    "assign_review_cohort",
    "build_canonical_listings",
    "build_canonical_shops",
    "calculate_cr10",
    "calculate_cr5",
    "calculate_entry_score",
    "calculate_new_shop_share",
    "calculate_price_summary",
    "calculate_rank_window_metrics",
    "calculate_recent_listing_share",
    "calculate_unique_shop_penetration",
    "classify_capability_status",
    "classify_verdict",
    "AIProvider",
    "AIResult",
    "AISettings",
    "NullAIProvider",
    "build_ai_provider",
    "load_ai_settings",
    "load_query_config",
    "load_threshold_config",
    "normalize_listing_id",
    "CanonicalListing",
    "CanonicalShop",
    "EntryScoreResult",
    "FamilyMetrics",
    "PriceSummary",
    "QueryDefinition",
    "QueryMetrics",
    "RankWindowMetrics",
    "RawObservation",
    "ResearchRun",
    "ResearchVerdict",
    "parse_active_listing_page",
    "parse_active_listing_record",
    "select_representative_pilot_queries",
]

__version__ = "0.1.0"
